name: Sync JS JIRA

on:
  schedule:
    - cron: 0 9-20 * * 1-5
  workflow_dispatch:

jobs:
  sync-jira:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run:
          python -m pip install requests jira
      - run:
          python RunUpdate.py
        env:
          JIRA_PAT: ${{ secrets.JIRA_PAT }}
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - run:
          cat GitToJira.log >> $GITHUB_STEP_SUMMARY
